### PR TITLE
feat: Record error using `tracing` instead of `errprintln`

### PR DESCRIPTION
**Pull request by merc1031**
This lets it be filtered, amended, enhanced in the rest of the tracing ecosystem we are already in

### CODE REVIEW

**Comment by krojew** [comment]
This will result in infinite loop, since the error will be picked up by the integration.

**Comment by merc1031** [comment]
Ah is that the reason!?

The reason i was trying to add this is, we recently had an  elastic apm
overload / outage in a different org that supports us, and since these
stderr logs dont undergo normal elastic formatting / processing they did
not show up and were not alertable.

Do you have another suggestion?

**Comment by krojew** [comment]
Unfortunately, I don't see any other way than simple print. You can't use the tracing framework for the reason above. You also can't store logs nad wait for Elastic to become available for obvious reasons.

**Comment by merc1031** [comment]
Understood. Feel free to decline this pr.
I'll experiment and see if there's anything I can think of.
Thanks!

**Pull request closed without merging**
